spring.application.name=desfile

# Conectar com o DB Localmente

spring.datasource.url=jdbc:postgresql://localhost:5432/desfile_db
spring.datasource.username=postgres
spring.datasource.password=aurash

# Criação de Tabelas Automaticas

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Desligar o Servidor WEB para ficar tudo no Terminal

spring.main.web-application-type=none